export * from "./audit-logs";
export * from "./authors";
export * from "./contracts";
export * from "./isbns";
export * from "./relations";
export * from "./returns";
export * from "./sales";
export * from "./statements";
export * from "./tenants";
export * from "./titles";
export * from "./users";

import type { auditLogs } from "./audit-logs";
import type { authors } from "./authors";
import type { contracts, contractTiers } from "./contracts";
import type { isbns } from "./isbns";
import type { returns } from "./returns";
import type { sales } from "./sales";
import type { statements } from "./statements";
import type { tenants } from "./tenants";
import type { titles } from "./titles";
import type { users } from "./users";

export type Tenant = typeof tenants.$inferSelect;
export type User = typeof users.$inferSelect;
export type Author = typeof authors.$inferSelect;
export type Title = typeof titles.$inferSelect;
export type ISBN = typeof isbns.$inferSelect;
export type Sale = typeof sales.$inferSelect;
export type Return = typeof returns.$inferSelect;
export type Contract = typeof contracts.$inferSelect;
export type ContractTier = typeof contractTiers.$inferSelect;
export type Statement = typeof statements.$inferSelect;
export type AuditLog = typeof auditLogs.$inferSelect;
export type UserRole = "owner" | "admin" | "editor" | "finance" | "author";
