export * from "./audit-logs";
export * from "./authors";
export * from "./contacts";
export * from "./contracts";
export * from "./form-1099";
export * from "./invoices";
export * from "./isbn-prefixes";
export * from "./isbns";
export * from "./relations";
export * from "./returns";
export * from "./sales";
export * from "./statements";
export * from "./tenants";
export * from "./title-authors";
export * from "./titles";
export * from "./users";

import type { auditLogs } from "./audit-logs";
import type { authors } from "./authors";
import type { contactRoles, contacts } from "./contacts";
import type { contracts, contractTiers } from "./contracts";
import type { form1099 } from "./form-1099";
import type { invoiceLineItems, invoices, payments } from "./invoices";
import type { isbnPrefixes } from "./isbn-prefixes";
import type { isbns } from "./isbns";
import type { returns } from "./returns";
import type { sales } from "./sales";
import type { statements } from "./statements";
import type { tenants } from "./tenants";
import type { titleAuthors } from "./title-authors";
import type { titles } from "./titles";
import type { users } from "./users";

export type Tenant = typeof tenants.$inferSelect;
export type User = typeof users.$inferSelect;
export type Author = typeof authors.$inferSelect;
export type Title = typeof titles.$inferSelect;
export type TitleAuthor = typeof titleAuthors.$inferSelect;
export type ISBN = typeof isbns.$inferSelect;
export type IsbnPrefix = typeof isbnPrefixes.$inferSelect;
export type Sale = typeof sales.$inferSelect;
export type Return = typeof returns.$inferSelect;
export type Contract = typeof contracts.$inferSelect;
export type ContractTier = typeof contractTiers.$inferSelect;
export type Statement = typeof statements.$inferSelect;
export type AuditLog = typeof auditLogs.$inferSelect;
export type Contact = typeof contacts.$inferSelect;
export type ContactRole = typeof contactRoles.$inferSelect;
export type Invoice = typeof invoices.$inferSelect;
export type InvoiceLineItem = typeof invoiceLineItems.$inferSelect;
export type Payment = typeof payments.$inferSelect;
export type Form1099 = typeof form1099.$inferSelect;
export type UserRole = "owner" | "admin" | "editor" | "finance" | "author";
