export * from "./api-keys";
export * from "./audit-logs";
export * from "./authors";
export * from "./channel-credentials";
export * from "./channel-feeds";
export * from "./codelists";
export * from "./contacts";
export * from "./contracts";
export * from "./csv-exports";
export * from "./csv-imports";
export * from "./form-1099";
export * from "./invoices";
export * from "./isbn-prefixes";
export * from "./isbns";
export * from "./notification-preferences";
export * from "./notifications";
export * from "./onboarding";
export * from "./onix-exports";
export * from "./onix-imports";
export * from "./platform-announcements";
export * from "./platform-audit-logs";
export * from "./production-projects";
export * from "./production-tasks";
export * from "./proof-files";
export * from "./rate-limit-overrides";
export * from "./relations";
export * from "./returns";
export * from "./sales";
export * from "./statements";
export * from "./tenants";
export * from "./title-authors";
export * from "./titles";
export * from "./users";
export * from "./webhook-deliveries";
export * from "./webhook-subscriptions";

import type { apiKeys } from "./api-keys";
import type { auditLogs } from "./audit-logs";
import type { authors } from "./authors";
import type { channelCredentials } from "./channel-credentials";
import type { channelFeeds } from "./channel-feeds";
import type { codelists, codelistValues } from "./codelists";
import type { contactRoles, contacts } from "./contacts";
import type { contracts, contractTiers } from "./contracts";
import type { csvExports } from "./csv-exports";
import type { csvImports } from "./csv-imports";
import type { form1099 } from "./form-1099";
import type { invoiceLineItems, invoices, payments } from "./invoices";
import type { isbnPrefixes } from "./isbn-prefixes";
import type { isbns } from "./isbns";
import type { onixExports } from "./onix-exports";
import type { onixImports } from "./onix-imports";
import type { returns } from "./returns";
import type { sales } from "./sales";
import type { statements } from "./statements";
import type { tenants } from "./tenants";
import type { titleAuthors } from "./title-authors";
import type { titles } from "./titles";
import type { users } from "./users";

export type Tenant = typeof tenants.$inferSelect;
export type User = typeof users.$inferSelect;
export type Author = typeof authors.$inferSelect;
export type Codelist = typeof codelists.$inferSelect;
export type CodelistValue = typeof codelistValues.$inferSelect;
export type Title = typeof titles.$inferSelect;
export type TitleAuthor = typeof titleAuthors.$inferSelect;
export type ISBN = typeof isbns.$inferSelect;
export type IsbnPrefix = typeof isbnPrefixes.$inferSelect;
export type Sale = typeof sales.$inferSelect;
export type Return = typeof returns.$inferSelect;
export type Contract = typeof contracts.$inferSelect;
export type ContractTier = typeof contractTiers.$inferSelect;
export type Statement = typeof statements.$inferSelect;
export type AuditLog = typeof auditLogs.$inferSelect;
export type Contact = typeof contacts.$inferSelect;
export type ContactRole = typeof contactRoles.$inferSelect;
export type Invoice = typeof invoices.$inferSelect;
export type InvoiceLineItem = typeof invoiceLineItems.$inferSelect;
export type Payment = typeof payments.$inferSelect;
export type Form1099 = typeof form1099.$inferSelect;
export type OnixExport = typeof onixExports.$inferSelect;
export type OnixImport = typeof onixImports.$inferSelect;
export type ChannelCredential = typeof channelCredentials.$inferSelect;
export type ChannelFeed = typeof channelFeeds.$inferSelect;
export type ApiKey = typeof apiKeys.$inferSelect;
export type CsvExport = typeof csvExports.$inferSelect;
export type CsvImport = typeof csvImports.$inferSelect;
export type UserRole = "owner" | "admin" | "editor" | "finance" | "author";

import type { webhookDeliveries } from "./webhook-deliveries";
import type { webhookSubscriptions } from "./webhook-subscriptions";
export type WebhookDelivery = typeof webhookDeliveries.$inferSelect;
export type WebhookSubscription = typeof webhookSubscriptions.$inferSelect;

import type { onboardingProgress } from "./onboarding";
export type OnboardingProgress = typeof onboardingProgress.$inferSelect;

import type { notifications } from "./notifications";
export type Notification = typeof notifications.$inferSelect;

import type { notificationPreferences } from "./notification-preferences";
export type NotificationPreference =
  typeof notificationPreferences.$inferSelect;

import type { productionProjects } from "./production-projects";
export type ProductionProject = typeof productionProjects.$inferSelect;

import type { productionTasks } from "./production-tasks";
export type ProductionTask = typeof productionTasks.$inferSelect;

import type { proofFiles } from "./proof-files";
export type ProofFile = typeof proofFiles.$inferSelect;
